window.RENTAL_DATA = {
  targetCount: 50,
  updated: "2026-07-29",
  checkedAt: "2026-07-29T10:14:00+01:00",
  headline: "I have searched far and wide for a house for Tess & Kevin and as of 29 July 2026, here are my suggestions...",
  recommendation: "Wetherby Gardens remains the best value. St Michaels Road is still the strongest two-car choice, while Gloster Close is the best currently verified house-and-garden option. The shortlist has deliberately been reduced to ten after a stricter live-page availability audit — fewer real options is better than a padded list of dead ones.",
  incomes: { kevin: 1730.97, tess: 1620 },
  changes: [
    { type: "removed", title: "Dead and uncertain listings removed", text: "Nine records were removed after direct pages showed let agreed, no longer on the market, or could not be reliably confirmed as live." },
    { type: "verified", title: "Exact-page checking is now mandatory", text: "A search result or cached portal preview no longer counts. Every active home must survive a current detail-page check." },
    { type: "ranking", title: "Shortlist reranked", text: "Only the ten strongest currently supportable listings remain while the search rebuilds toward 50." }
  ],
  properties: [
    {rank:1,name:"Wetherby Gardens",area:"Farnborough, GU14",rent:1200,score:93,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Listed as available on the current portal",duplicateKey:"wetherby-gardens-gu14-1200",epc:"TBC",councilBand:"TBC",parking:"Resident + visitor",parkingConfidence:0.9,garden:"Communal gardens",outdoorConfidence:0.95,distanceMiles:10.5,guildfordAccess:"Good road access via A331; Farnborough rail links nearby",tags:["garden","parking2","under1400"],label:"Best value",link:"https://www.rightmove.co.uk/properties/102409619",image:"https://media.rightmove.co.uk/dir/crop/10%3A9-16%3A9/property-photo/44538042b/102409619/44538042b6f12c3df4fae2a9296219e1_max_476x317.jpeg",summary:"The strongest blend of low rent, two usable bedrooms, updated interiors and practical resident or visitor parking.",pros:["£1,200 rent","Parking flexibility","Communal gardens","Updated kitchen and bathroom"],cons:["No private garden","EPC and council-tax band need confirming"],bills:{councilTax:157,energy:120,water:38,broadband:30,contents:15}},
    {rank:2,name:"St Michaels Road",area:"Aldershot, GU12",rent:1400,score:90,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Listed on 9 July 2026 and present in current rental results",duplicateKey:"st-michaels-road-gu12-1400",epc:"TBC",councilBand:"TBC",parking:"Two off-street spaces",parkingConfidence:1,garden:"Not stated",outdoorConfidence:0.2,distanceMiles:11.5,guildfordAccess:"Direct A323/A31 road route toward Guildford",tags:["parking2"],label:"Best for 2 cars",link:"https://www.rightmove.co.uk/properties/90694551",image:"https://media.rightmove.co.uk/dir/crop/10%3A9-16%3A9/property-photo/ab7cfb2ad/90694551/ab7cfb2addd16b4a4e3ed7bdb4d1589f_max_476x317.jpeg",summary:"Two proper parking spaces are rare. That practical advantage matters more for you than a prettier lobby with one awkward visitor bay.",pros:["Two double bedrooms","Two off-street spaces","Private entrance","Useful road access"],cons:["No garden confirmed","EPC and council tax need confirming"],bills:{councilTax:170,energy:135,water:40,broadband:30,contents:15}},
    {rank:3,name:"Gloster Close",area:"Ash Vale, GU12",rent:1495,score:89,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available from 11 September 2026",duplicateKey:"gloster-close-ash-vale-gu12-1495",epc:"TBC",councilBand:"D",parking:"Allocated parking",parkingConfidence:0.95,garden:"Private rear garden",outdoorConfidence:1,distanceMiles:9.5,guildfordAccess:"Ash Vale location with strong A331 access toward Guildford",tags:["garden","under1500"],label:"Best house option",link:"https://www.rightmove.co.uk/properties/89608194",image:"",summary:"A two-bedroom semi-detached house with two double bedrooms, a cul-de-sac position, private garden and allocated parking.",pros:["Private garden","Allocated parking","Two double bedrooms","Downstairs cloakroom"],cons:["Stretch-budget rent","Available from September","EPC needs confirming"],bills:{councilTax:190,energy:140,water:40,broadband:32,contents:16}},
    {rank:4,name:"Peabody Road",area:"Farnborough, GU14",rent:1250,score:87,source:"OnTheMarket",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Current detail listing",duplicateKey:"peabody-road-farnborough-gu14-1250",epc:"TBC",councilBand:"B",parking:"Street parking",parkingConfidence:0.45,garden:"Private garden",outdoorConfidence:1,distanceMiles:10.2,guildfordAccess:"North Camp area with useful A331 access",tags:["garden","under1400"],label:"Best garden value",link:"https://www.onthemarket.com/details/17536606/",image:"",summary:"A current two-bedroom North Camp option with a private garden and a lower rent than the older portal record previously shown.",pros:["£1,250 rent","Private garden","Two double bedrooms","Council Tax Band B"],cons:["Street parking rather than allocated spaces","EPC needs confirming"],bills:{councilTax:162,energy:128,water:40,broadband:32,contents:15}},
    {rank:5,name:"Lynchford Road",area:"Farnborough, GU14",rent:1250,score:87,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available from 10 July 2026",duplicateKey:"lynchford-road-farnborough-gu14-1250",epc:"D",councilBand:"B",parking:"Not stated",parkingConfidence:0.2,garden:"No outdoor space stated",outdoorConfidence:0.1,distanceMiles:9.8,guildfordAccess:"Close to North Camp and useful road links toward Guildford",tags:["under1400"],label:"Best low-cost Farnborough flat",link:"https://www.zoopla.co.uk/to-rent/details/67360225/",image:"",summary:"A well-presented first-floor two-bedroom flat near North Camp with Band B council tax and a relatively low rent.",pros:["£1,250 rent","Council Tax Band B","Two good-sized bedrooms","North Camp amenities nearby"],cons:["Electric heating","No parking confirmed","No garden stated","Pets and children not permitted"],bills:{councilTax:162,energy:135,water:36,broadband:30,contents:14}},
    {rank:6,name:"Station Approach",area:"Ash Vale, GU12",rent:1100,score:85,source:"OnTheMarket",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available from 21 August 2026",duplicateKey:"station-approach-ash-vale-gu12-1100",epc:"C",councilBand:"C",parking:"Parking stated",parkingConfidence:0.85,garden:"Communal garden",outdoorConfidence:0.9,distanceMiles:9.1,guildfordAccess:"Immediately beside Ash Vale station with rail access toward Guildford",tags:["garden","under1400","epcC"],label:"Cheapest transport-friendly option",link:"https://www.onthemarket.com/details/19900629/",image:"",summary:"A low-rent two-bedroom apartment beside Ash Vale station with parking, communal garden and EPC C.",pros:["£1,100 rent","Station access","EPC C","Communal garden","Parking stated"],cons:["Available from late August","Confirm exact parking allocation"],bills:{councilTax:178,energy:105,water:36,broadband:30,contents:14}},
    {rank:7,name:"High Street Maisonette",area:"Aldershot, GU12",rent:1300,score:84,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available now",duplicateKey:"high-street-maisonette-aldershot-gu12-1300",epc:"D",councilBand:"A",parking:"One allocated space",parkingConfidence:0.9,garden:"Private terrace",outdoorConfidence:0.95,distanceMiles:11.3,guildfordAccess:"Aldershot rail and road links toward Guildford",tags:["garden","under1400"],label:"Best low-bill option",link:"https://www.rightmove.co.uk/properties/89460432",image:"https://media.rightmove.co.uk/dir/property-photo/e39d06b93/89460432/e39d06b9367061af60a1ed492649bcc4_max_656x437.jpeg",summary:"Band A council tax, an allocated space and a private terrace make the total cost stronger than the headline rent suggests.",pros:["Band A council tax","Private terrace","Allocated parking","Refurbished in 2026"],cons:["High Street setting","EPC D","Second-car parking not guaranteed"],bills:{councilTax:139,energy:108,water:36,broadband:32,contents:15}},
    {rank:8,name:"Bakehouse Mews",area:"Aldershot, GU11",rent:1150,score:82,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available early August 2026",duplicateKey:"bakehouse-mews-gu11-1150",epc:"D",councilBand:"A",parking:"Not stated",parkingConfidence:0.2,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:11.4,guildfordAccess:"Aldershot station and road links toward Guildford",tags:["under1400"],label:"Best cheap backup",link:"https://www.rightmove.co.uk/properties/90946707",image:"",summary:"Excellent monthly cost and low council tax, although parking and outdoor space remain unconfirmed.",pros:["£1,150 rent","Council Tax Band A","Close to station and town","Available early August"],cons:["Parking unconfirmed","Garden unconfirmed","EPC D"],bills:{councilTax:139,energy:105,water:35,broadband:27,contents:14}},
    {rank:9,name:"Holly Road",area:"Aldershot, GU12",rent:1400,score:80,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Current detail listing",duplicateKey:"holly-road-aldershot-gu12-1400",epc:"D",councilBand:"C",parking:"On-street parking",parkingConfidence:0.45,garden:"Private rear garden",outdoorConfidence:1,distanceMiles:11.2,guildfordAccess:"A331 and A323 road access toward Guildford",tags:["garden","under1400"],label:"Garden option",link:"https://www.rightmove.co.uk/properties/174252266",image:"",summary:"A two-bedroom terraced house with a private garden, Victorian character and rent at the comfort ceiling.",pros:["Private rear garden","Two-bedroom house","Council Tax Band C","Long-term let"],cons:["On-street parking only","EPC D","Second-car practicality weaker"],bills:{councilTax:178,energy:135,water:39,broadband:30,contents:16}},
    {rank:10,name:"Queens Road",area:"Aldershot, GU11",rent:1100,score:73,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T10:14:00+01:00",status:"Available",availabilityStatus:"Available now",duplicateKey:"queens-road-aldershot-gu11-1100",epc:"D",councilBand:"TBC",parking:"Ask agent",parkingConfidence:0.2,garden:"Shared communal garden",outdoorConfidence:0.85,distanceMiles:11.5,guildfordAccess:"Aldershot station and A31 corridor",tags:["garden","under1400"],label:"Cheapest garden backup",link:"https://www.rightmove.co.uk/properties/90526110",image:"",summary:"Excellent for saving and available now, though parking and equal bedroom quality need checking.",pros:["£1,100 rent","Shared communal garden","Gas central heating","Available now"],cons:["Parking unclear","Council tax needs confirming","Bedroom sizes need checking"],bills:{councilTax:145,energy:95,water:34,broadband:25,contents:11}}
  ]
};

/* App enhancements: keep this loader block when refreshing rental data. */
(()=>{
  const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css?v=20260727';document.head.appendChild(css);
  const script=document.createElement('script');script.src='enhancements.js?v=20260727';script.defer=true;document.head.appendChild(script);
})();