window.RENTAL_DATA = {
  targetCount: 50,
  updated: "2026-07-29",
  checkedAt: "2026-07-29T07:56:00+01:00",
  headline: "I have searched far and wide for a house for Tess & Kevin and as of 29 July 2026, here are my suggestions...",
  recommendation: "Somerset Road is today's strongest addition because it combines EPC B, two bathrooms, communal garden and two allocated parking spaces at the £1,400 comfort ceiling. Wetherby Gardens remains the best overall value, while Station Approach is the new cheapest verified two-bedroom option. The shortlist now has 19 active, deduplicated homes and will continue expanding toward 50.",
  incomes: { kevin: 1730.97, tess: 1620 },
  changes: [
    { type: "new", title: "Five verified homes added", text: "Somerset Road, Station Approach, Yeovil Close, Thameswey House and Kings Avenue have joined the shortlist." },
    { type: "ranking", title: "Somerset Road enters the top three", text: "Two allocated parking spaces, EPC B and communal gardens make it unusually well matched to the brief." },
    { type: "verified", title: "Daily market check complete", text: "The active shortlist was rechecked across major portals on 29 July 2026." }
  ],
  properties: [
    {rank:1,name:"Wetherby Gardens",area:"Farnborough, GU14",rent:1200,score:93,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"wetherby-gardens-gu14-1200",epc:"TBC",councilBand:"TBC",parking:"Resident + visitor",parkingConfidence:0.9,garden:"Communal gardens",outdoorConfidence:0.95,distanceMiles:10.5,guildfordAccess:"Good road access via A331; Farnborough rail links nearby",tags:["garden","parking2","under1400"],label:"Best value",link:"https://www.rightmove.co.uk/properties/102409619",image:"https://media.rightmove.co.uk/dir/crop/10%3A9-16%3A9/property-photo/44538042b/102409619/44538042b6f12c3df4fae2a9296219e1_max_476x317.jpeg",summary:"The strongest blend of low rent, two usable bedrooms, updated interiors and practical resident or visitor parking.",pros:["£1,200 rent","Parking flexibility","Communal gardens","Updated kitchen and bathroom"],cons:["No private garden","EPC and council-tax band need confirming"],bills:{councilTax:157,energy:120,water:38,broadband:30,contents:15}},
    {rank:2,name:"St Michaels Road",area:"Aldershot, GU12",rent:1400,score:90,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"st-michaels-road-gu12-1400",epc:"TBC",councilBand:"TBC",parking:"Two off-street spaces",parkingConfidence:1,garden:"Not stated",outdoorConfidence:0.2,distanceMiles:11.5,guildfordAccess:"Direct A323/A31 road route toward Guildford",tags:["parking2"],label:"Best for 2 cars",link:"https://www.rightmove.co.uk/properties/90694551",image:"https://media.rightmove.co.uk/dir/crop/10%3A9-16%3A9/property-photo/ab7cfb2ad/90694551/ab7cfb2addd16b4a4e3ed7bdb4d1589f_max_476x317.jpeg",summary:"Two proper parking spaces are rare. That practical advantage matters more for you than a prettier lobby with one awkward visitor bay.",pros:["Two double bedrooms","Two off-street spaces","Private entrance","Useful road access"],cons:["No garden confirmed","EPC and council tax need confirming"],bills:{councilTax:170,energy:135,water:40,broadband:30,contents:15}},
    {rank:3,name:"Somerset Road",area:"Farnborough, GU14",rent:1400,score:90,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available immediately",duplicateKey:"somerset-road-farnborough-gu14-1400",epc:"B",councilBand:"C",parking:"Two allocated spaces",parkingConfidence:1,garden:"Communal garden",outdoorConfidence:0.95,distanceMiles:10,guildfordAccess:"South Farnborough with easy A331/M3 access toward Guildford",tags:["garden","parking2","epcC","under1400"],label:"Best all-round new option",link:"https://www.zoopla.co.uk/to-rent/details/41802463/",image:"",summary:"A modern two-bedroom, two-bathroom apartment with EPC B, a communal garden and two allocated parking spaces.",pros:["Two allocated parking spaces","EPC B","Communal garden","Two bathrooms","Available immediately"],cons:["Rent is at the comfort ceiling","Apartment rather than house"],bills:{councilTax:178,energy:95,water:40,broadband:32,contents:15}},
    {rank:4,name:"Gloster Close",area:"Ash Vale, GU12",rent:1495,score:89,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available from 11 September 2026",duplicateKey:"gloster-close-ash-vale-gu12-1495",epc:"TBC",councilBand:"TBC",parking:"Allocated parking",parkingConfidence:0.95,garden:"Private rear garden",outdoorConfidence:1,distanceMiles:9.5,guildfordAccess:"Ash Vale location with strong A331 access toward Guildford",tags:["garden","under1500"],label:"Best house option",link:"https://www.rightmove.co.uk/properties/89608194",image:"",summary:"A two-bedroom semi-detached house with two double bedrooms, a cul-de-sac position, private garden and allocated parking.",pros:["Private garden","Allocated parking","Two double bedrooms","Downstairs cloakroom"],cons:["Stretch-budget rent","Available from September","Council tax and EPC need confirming"],bills:{councilTax:175,energy:140,water:40,broadband:32,contents:16}},
    {rank:5,name:"Peabody Road",area:"Farnborough, GU14",rent:1300,score:88,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"peabody-road-gu14-1300",epc:"TBC",councilBand:"TBC",parking:"Allocated parking",parkingConfidence:0.95,garden:"Not stated",outdoorConfidence:0.2,distanceMiles:10.2,guildfordAccess:"North Camp area with useful A331 access",tags:["under1400"],label:"Best middle ground",link:"https://www.rightmove.co.uk/properties/91129149",image:"https://media.rightmove.co.uk/dir/crop/10%3A9-16%3A9/property-photo/e0f944078/91129149/e0f94407880d74923b21662d24dce45f_max_476x317.jpeg",summary:"A sensible mid-priced option with two useful bedrooms, allocated parking and an additional WC.",pros:["£1,300 rent","Allocated parking","Two useful bedrooms","Additional WC"],cons:["Garden not confirmed","EPC and council tax need checking"],bills:{councilTax:155,energy:128,water:40,broadband:32,contents:15}},
    {rank:6,name:"Lynchford Road",area:"Farnborough, GU14",rent:1250,score:87,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available now",duplicateKey:"lynchford-road-farnborough-gu14-1250",epc:"D",councilBand:"B",parking:"Not stated",parkingConfidence:0.2,garden:"No outdoor space stated",outdoorConfidence:0.1,distanceMiles:9.8,guildfordAccess:"Close to North Camp and useful road links toward Guildford",tags:["under1400"],label:"Best low-cost Farnborough flat",link:"https://www.zoopla.co.uk/to-rent/details/67360225/",image:"",summary:"A well-presented first-floor two-bedroom flat near North Camp with Band B council tax and a relatively low rent.",pros:["£1,250 rent","Council Tax Band B","Two good-sized bedrooms","North Camp amenities nearby"],cons:["Electric heating","No parking confirmed","No garden stated","Pets and children not permitted"],bills:{councilTax:162,energy:135,water:36,broadband:30,contents:14}},
    {rank:7,name:"Quarry Street",area:"Guildford, GU1",rent:1475,score:85,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"quarry-street-guildford-gu1-1475",epc:"C",councilBand:"TBC",parking:"Secure space for 1 car",parkingConfidence:0.9,garden:"Communal gardens",outdoorConfidence:0.95,distanceMiles:0.5,guildfordAccess:"Central Guildford; walkable to town centre and station",tags:["garden","guildford","epcC"],label:"Best Guildford location",link:"https://www.rightmove.co.uk/properties/164826218",image:"https://media.rightmove.co.uk/dir/property-photo/6d33eb36c/164826218/6d33eb36cb11dc56c4cae6cad26c519c_max_656x437.jpeg",summary:"The strongest Guildford-address compromise: central, EPC C, communal gardens and secure covered parking.",pros:["Central Guildford","EPC C","Secure parking","Communal gardens"],cons:["Higher rent","Smaller second bedroom","Second-car parking unresolved"],bills:{councilTax:175,energy:135,water:40,broadband:35,contents:15}},
    {rank:8,name:"High Street Maisonette",area:"Aldershot, GU12",rent:1300,score:84,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"high-street-maisonette-aldershot-gu12-1300",epc:"D",councilBand:"A",parking:"One allocated space",parkingConfidence:0.9,garden:"Private terrace",outdoorConfidence:0.95,distanceMiles:11.3,guildfordAccess:"Aldershot rail and road links toward Guildford",tags:["garden","under1400"],label:"Best low-bill option",link:"https://www.rightmove.co.uk/properties/89460432",image:"https://media.rightmove.co.uk/dir/property-photo/e39d06b93/89460432/e39d06b9367061af60a1ed492649bcc4_max_656x437.jpeg",summary:"Band A council tax, an allocated space and a private terrace make the total cost stronger than the headline rent suggests.",pros:["Band A council tax","Private terrace","Allocated parking","Refurbished in 2026"],cons:["High Street setting","EPC D","Second-car parking not guaranteed"],bills:{councilTax:139,energy:108,water:36,broadband:32,contents:15}},
    {rank:9,name:"Station Approach",area:"Ash Vale, GU12",rent:1100,score:84,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"station-approach-ash-vale-gu12-1100",epc:"TBC",councilBand:"TBC",parking:"Not confirmed",parkingConfidence:0.25,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:9.1,guildfordAccess:"Very close to Ash Vale station with direct rail access toward Guildford",tags:["under1400"],label:"Cheapest new option",link:"https://www.zoopla.co.uk/to-rent/details/73673659/",image:"",summary:"A modern ground-floor two-bedroom apartment immediately beside Ash Vale station at a notably low rent.",pros:["£1,100 rent","Ash Vale station access","Ground-floor apartment","Two bedrooms"],cons:["Parking unconfirmed","Outdoor space unconfirmed","EPC and council tax need checking"],bills:{councilTax:160,energy:125,water:36,broadband:30,contents:14}},
    {rank:10,name:"Elleray Court",area:"Ash Vale, GU12",rent:1350,score:83,source:"OpenRent",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available now",duplicateKey:"elleray-court-ash-vale-gu12-1350",epc:"TBC",councilBand:"TBC",parking:"Not confirmed",parkingConfidence:0.3,garden:"Not stated",outdoorConfidence:0.2,distanceMiles:9.2,guildfordAccess:"Ash Vale station and A331 provide useful Guildford access",tags:["under1400"],label:"Best Ash Vale flat",link:"https://www.zoopla.co.uk/to-rent/property/2-bedrooms/ash-vale/",image:"",summary:"A two-bedroom OpenRent flat in Ash Vale at a manageable rent, with strong transport links but limited confirmed detail.",pros:["Ash Vale location","£1,350 rent","Available now","Two bedrooms"],cons:["Parking unconfirmed","EPC and council tax unconfirmed","Direct OpenRent detail page not indexed"],bills:{councilTax:165,energy:125,water:38,broadband:30,contents:15}},
    {rank:11,name:"Yeovil Close",area:"Farnborough, GU14",rent:1350,score:82,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"yeovil-close-farnborough-gu14-1350",epc:"TBC",councilBand:"TBC",parking:"Not confirmed",parkingConfidence:0.35,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:10,guildfordAccess:"North Camp location with easy A331 access",tags:["under1400"],label:"Refurbished North Camp option",link:"https://www.zoopla.co.uk/to-rent/details/73649009/",image:"",summary:"A refurbished two-bedroom flat in North Camp with a manageable rent and useful transport access.",pros:["Refurbished","£1,350 rent","North Camp location","Two bedrooms"],cons:["Parking not confirmed","Garden not stated","EPC and council tax need confirming"],bills:{councilTax:165,energy:125,water:38,broadband:30,contents:15}},
    {rank:12,name:"Bakehouse Mews",area:"Aldershot, GU11",rent:1150,score:82,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"bakehouse-mews-gu11-1150",epc:"D",councilBand:"A",parking:"Ask agent",parkingConfidence:0.25,garden:"Ask agent",outdoorConfidence:0.25,distanceMiles:11.4,guildfordAccess:"Aldershot station and road links toward Guildford",tags:["under1400"],label:"Best cheap backup",link:"https://www.rightmove.co.uk/properties/90946707",image:"",summary:"Excellent monthly cost and low council tax, but parking remains the big unanswered question.",pros:["£1,150 rent","Council Tax Band A","Close to station and town"],cons:["Parking unconfirmed","Garden unconfirmed","EPC D"],bills:{councilTax:139,energy:105,water:35,broadband:27,contents:14}},
    {rank:13,name:"Ash Road",area:"Aldershot, GU12",rent:1250,score:81,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"ash-road-aldershot-gu12-1250",epc:"C",councilBand:"B",parking:"One off-street space",parkingConfidence:0.9,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:10.8,guildfordAccess:"Road access via A323/A31",tags:["under1400","epcC"],label:"Best efficient flat",link:"https://www.zoopla.co.uk/to-rent/details/67695822/",image:"",summary:"Two double bedrooms, EPC C and Band B council tax make this financially tidy. The weak point is one confirmed car space.",pros:["Two double bedrooms","EPC C","Band B","Off-street parking"],cons:["One confirmed space","No garden mentioned"],bills:{councilTax:162,energy:105,water:36,broadband:32,contents:15}},
    {rank:14,name:"Holly Road",area:"Aldershot, GU12",rent:1400,score:80,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"holly-road-aldershot-gu12-1400",epc:"D",councilBand:"C",parking:"On-street parking",parkingConfidence:0.45,garden:"Private rear garden",outdoorConfidence:1,distanceMiles:11.2,guildfordAccess:"A331 and A323 road access toward Guildford",tags:["garden"],label:"Garden option",link:"https://www.rightmove.co.uk/properties/174252266",image:"",summary:"A two-bedroom terraced house with a private garden, Victorian character and a rent right at the comfort ceiling.",pros:["Private rear garden","Two-bedroom house","Council Tax Band C","Long-term let"],cons:["On-street parking only","EPC D","Second-car practicality weaker"],bills:{councilTax:178,energy:135,water:39,broadband:30,contents:16}},
    {rank:15,name:"Thameswey House",area:"Farnborough, GU14",rent:1400,score:79,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available early October",duplicateKey:"thameswey-house-camp-road-gu14-1400",epc:"TBC",councilBand:"TBC",parking:"Not confirmed",parkingConfidence:0.35,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:10.1,guildfordAccess:"Camp Road and North Camp area with good A331 access",tags:["under1400"],label:"Modern October option",link:"https://www.zoopla.co.uk/to-rent/details/73674836/",image:"",summary:"A modern first-floor two-bedroom apartment near North Camp, available from early October.",pros:["Modern apartment","£1,400 rent","North Camp amenities","Useful road links"],cons:["Not available until October","Parking unconfirmed","EPC and council tax need checking"],bills:{councilTax:170,energy:125,water:40,broadband:32,contents:15}},
    {rank:16,name:"Aspen Grove",area:"Aldershot, GU12",rent:1350,score:77,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"aspen-grove-aldershot-gu12-1350",epc:"TBC",councilBand:"TBC",parking:"Check with agent",parkingConfidence:0.3,garden:"Not stated",outdoorConfidence:0.15,distanceMiles:11.1,guildfordAccess:"Close to Aldershot town centre and mainline station",tags:["under1400"],label:"Central apartment",link:"https://www.rightmove.co.uk/properties/91161741",image:"",summary:"A newer two-bedroom apartment near the centre and station, but several practical details still need confirming.",pros:["Two bedrooms","Central access","Within comfort range"],cons:["Parking unclear","No garden stated","EPC and council tax unclear"],bills:{councilTax:165,energy:125,water:40,broadband:35,contents:15}},
    {rank:17,name:"Kings Avenue",area:"Tongham, GU10",rent:1350,score:77,source:"Zoopla",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"kings-avenue-tongham-gu10-1350",epc:"TBC",councilBand:"TBC",parking:"Not confirmed",parkingConfidence:0.3,garden:"Not stated",outdoorConfidence:0.2,distanceMiles:8.5,guildfordAccess:"Tongham location with A31 access toward Guildford",tags:["under1400"],label:"Closer-to-Guildford budget option",link:"https://www.zoopla.co.uk/to-rent/details/73638332/",image:"",summary:"A two-bedroom ground-floor maisonette in Tongham, closer to Guildford than most Aldershot options.",pros:["£1,350 rent","Ground-floor maisonette","Closer to Guildford","Village setting"],cons:["Parking unconfirmed","Outdoor space unconfirmed","EPC and council tax need checking"],bills:{councilTax:168,energy:125,water:38,broadband:30,contents:15}},
    {rank:18,name:"Wolseley Road",area:"Aldershot, GU11",rent:1500,score:75,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available",duplicateKey:"wolseley-road-aldershot-gu11-1500",epc:"TBC",councilBand:"TBC",parking:"Check with agent",parkingConfidence:0.25,garden:"Check with agent",outdoorConfidence:0.25,distanceMiles:11.7,guildfordAccess:"Aldershot road and rail links toward Guildford",tags:[],label:"Proper house backup",link:"https://www.rightmove.co.uk/properties/91157490",image:"",summary:"A proper terraced house with two double bedrooms and two reception rooms, but it uses the full stretch budget.",pros:["Proper house","Two double bedrooms","Two reception rooms"],cons:["£1,500 rent","Parking and garden need confirmation","Less room to save"],bills:{councilTax:185,energy:145,water:40,broadband:35,contents:15}},
    {rank:19,name:"Queens Road",area:"Aldershot, GU11",rent:1100,score:73,source:"Rightmove",sourceType:"portal",verifiedAt:"2026-07-29T07:56:00+01:00",status:"Available",availabilityStatus:"Available now",duplicateKey:"queens-road-aldershot-gu11-1100",epc:"D",councilBand:"TBC",parking:"Ask agent",parkingConfidence:0.2,garden:"Communal garden",outdoorConfidence:0.85,distanceMiles:11.5,guildfordAccess:"Aldershot station and A31 corridor",tags:["garden","under1400"],label:"Cheapest garden backup",link:"https://www.rightmove.co.uk/properties/90526110",image:"",summary:"Excellent for saving and available now, though parking and equal bedroom quality need checking.",pros:["£1,100 rent","Communal garden","Gas central heating","Available now"],cons:["Parking unclear","Council tax needs confirming","Bedroom sizes need checking"],bills:{councilTax:145,energy:95,water:34,broadband:25,contents:11}}
  ]
};

/* App enhancements: keep this loader block when refreshing rental data. */
(()=>{
  const css=document.createElement('link');css.rel='stylesheet';css.href='enhancements.css?v=20260727';document.head.appendChild(css);
  const script=document.createElement('script');script.src='enhancements.js?v=20260727';script.defer=true;document.head.appendChild(script);
})();